server:
  profules:
    active:
---
#spring 配置
spring:
  profules: dev
    application:
      name: springcloud-config-dev
---
spring:
  profules: test
    application:
      name: springcloud-config-test